from playwright.sync_api import sync_playwright
import os; URL='file://'+os.path.abspath(os.path.join(os.path.dirname(__file__),'..','out','index.html'))
with sync_playwright() as p:
    b=p.chromium.launch(); pg=b.new_page(viewport={'width':1440,'height':900},locale='cs-CZ',timezone_id='Europe/Prague'); errs=[]
    pg.on('pageerror', lambda e: errs.append(str(e))); pg.route('**/fonts.googleapis.com/**', lambda r: r.abort())
    pg.goto(URL); pg.wait_for_timeout(200)
    pg.evaluate('localLogin("client")')
    # měření – uložit dnešní váhu přes UI
    pg.evaluate("go('pokrok');A.measSheet(todayISO(),true)"); pg.wait_for_timeout(100); pg.fill('#m_weight','131,9'); pg.fill('#m_waist','119'); pg.click('.modal >> text=Uložit zápis'); pg.wait_for_timeout(150)
    print('meas saved:', pg.evaluate("Meas().length"), pg.evaluate("Meas()[0]"))
    # týden – vybrat snídani přes UI select v pondělí
    pg.evaluate("go('tyden')"); pg.evaluate("A.planSel(0,0,'Tvarohová mísa s ovocem a oříšky')"); pg.wait_for_timeout(100)
    print('week plan mon:', pg.evaluate("getWeek(App.week).plan[0]"))
    pg.evaluate("A.copyWeek()") ; 
    # dnes – změnit jídlo, vyměnit surovinu, upravit gramy, pátek piva
    pg.evaluate("App.date=addDays(App.week,0);go('dnes')")
    pg.evaluate("A.mealSheet('snidane')"); pg.wait_for_timeout(150)   # jídlo se upravuje ve spodním listu
    pg.evaluate("document.querySelector('.modal .pickbtn').click()"); pg.wait_for_timeout(150); pg.fill('#pkq','míchaná'); pg.wait_for_timeout(100); print('picker hits:', pg.evaluate("document.querySelectorAll('.pitem').length")); pg.evaluate("window._pick('Míchaná vejce se šunkou a chlebem')"); pg.wait_for_timeout(100)
    print('sel:', pg.evaluate("getDay(App.date).meals.snidane"))
    pg.evaluate("document.querySelectorAll('.modal details.gdet').forEach(d=>d.open=true)")
    pg.click('.modal .irow .pickbtn >> nth=0'); pg.wait_for_timeout(150)   # výměna suroviny přes panel s hledáním
    pg.fill('#fp-q','tofu'); pg.wait_for_timeout(150); print('panel surovin našel:', pg.evaluate("document.querySelectorAll('.pitem').length"))
    pg.evaluate("window._fppick('Tofu')"); pg.wait_for_timeout(150)
    pg.fill('.modal .irow input.g >> nth=1','80'); pg.press('.modal .irow input.g >> nth=1','Tab'); pg.wait_for_timeout(150)
    print('edits:', pg.evaluate("JSON.stringify(getDay(App.date).meals.snidane)"))
    pg.evaluate("UI.closeModal();A.dayCheck()"); pg.wait_for_timeout(100)
    print('checks text:', pg.evaluate("[...document.querySelectorAll('.modal .checks .chk')].map(d=>d.textContent)")); pg.evaluate("UI.closeModal()")
    pg.evaluate("A.dayField('beers','6','Piva')"); pg.wait_for_timeout(100)
    print('friday hero:', pg.evaluate("document.querySelector('#hero .rg').textContent.trim()"), pg.evaluate("(document.querySelector('#hero .rnote')||{textContent:''}).textContent.trim()"))
    pg.evaluate("A.removeItem('snidane',0);A.extraAdd('snidane');A.extraFood('snidane',0,'Tofu');A.extraG('snidane',0,150)"); print('remove/extra:', pg.evaluate("JSON.stringify(getDay(App.date).meals.snidane)"), pg.evaluate("calcDay(S(),Foods(),Recipes(),effectiveDay(App.date),currentWeight()).courses[0].items.map(i=>i.food+':'+i.g).join(',')"))
    pg.evaluate("A.resetCourse('snidane')");
    pg.evaluate("toggleFav('Míchaná vejce se šunkou a chlebem')"); print('fav:', pg.evaluate("Prefs().favs"), 'recent:', pg.evaluate("Prefs().recent.slice(0,2)"))
    pg.evaluate("generateWeek(App.week,'all')"); print('gen week:', pg.evaluate("(()=>{const wk=getWeek(App.week);const s=S();return wk.plan.map(d=>calcPlanDay(s,Foods(),Recipes(),d,currentWeight()).status).join(' | ')+' uniq:'+new Set(wk.plan.flat()).size})()"))
    print('žádné vzkazy na Dnes:', pg.evaluate("App.date=todayISO();go('dnes');!document.querySelector('.now .bubble') && !document.querySelector('.modal')"))
    print('coach line:', pg.evaluate("coachLine(todayISO()).main"))
    print('plausible:', pg.evaluate("JSON.stringify(weightPlausible(121, todayISO()))"))
    pg.evaluate("A.editFood(null,'own')"); pg.fill('#fn','Moje proteinová tyčinka'); pg.fill('#fk','380'); pg.fill('#fp','30'); pg.fill('#fs','35'); pg.fill('#ff','12'); pg.click('#fsave'); pg.wait_for_timeout(100); print('own food:', pg.evaluate("Foods().filter(f=>f.own).map(f=>f.name+':'+f.kcal)"))
    print('after reset:', pg.evaluate("JSON.stringify(getDay(App.date).meals.snidane)"))
    # vlastní recept
    pg.evaluate("go('recepty');A.editOwn()"); pg.fill('#re-n','Testovací omeleta'); pg.evaluate("window._reAdd()"); pg.wait_for_timeout(150); pg.fill('#fp-q','vejce'); pg.wait_for_timeout(100); print('food picker hits:', pg.evaluate("document.querySelectorAll('.pitem').length")); pg.evaluate("window._fppick('Vejce')"); pg.evaluate("window._reG(0,300)")
    pg.evaluate("window._reAdd()"); pg.wait_for_timeout(150); pg.evaluate("window._fppick('Chléb konzumní (Šumava)')"); pg.evaluate("window._reG(1,80)"); pg.wait_for_timeout(100)
    print('own hint:', pg.evaluate("document.querySelector('.modal .status').textContent"))
    pg.click('#re-save'); pg.wait_for_timeout(100); print('own recipes:', pg.evaluate("Recipes().filter(r=>r.own).map(r=>r.name)"), 'in menu:', pg.evaluate("recipesFor('Snídaně').some(r=>r.name==='Testovací omeleta')"))
    # export JSON obsah
    print('export keys:', pg.evaluate("(()=>{const uid=Store.ownerId();return TABLES.map(t=>t+':'+Store.db[t].filter(r=>r.user_id===uid).length)})()"))
    # coach: nastavení + editace potraviny + seed
    # úkoly, snědeno, uzavření
    pg.evaluate("App.date=todayISO();go('dnes')"); print('tasks:', pg.evaluate("dayTasks(todayISO()).map(t=>t.id+':'+(t.done?1:0)).join(' ')"))
    pg.evaluate("A.eaten('snidane',true)"); print('eaten:', pg.evaluate("getDay(todayISO()).meals.snidane.eaten"))
    pg.evaluate("A.suggestOne('obed')"); print('suggestOne:', pg.evaluate("getDay(todayISO()).meals.obed.sel"), 'toast:', pg.evaluate("document.querySelector('#toast span').textContent"))
    pg.evaluate("Undo.undo()"); print('after undo:', pg.evaluate("getDay(todayISO()).meals.obed.sel"))
    pg.evaluate("A.editFood(null,'own',null,'f1')"); pg.fill('#fk','999'); pg.click('#fsave'); pg.wait_for_timeout(100); print('kopie suroviny:', pg.evaluate("JSON.stringify(Foods().filter(f=>f.name.startsWith('Hovězí přední')).map(f=>[f.name,f.kcal,!!f.own]))"))
    pg.evaluate("A.editRecipe('r1')"); pg.wait_for_timeout(150); pg.click('#re-save'); pg.wait_for_timeout(150); print('kopie receptu:', pg.evaluate("JSON.stringify(Recipes().filter(r=>r.name.startsWith(Recipes().find(x=>x.id==='r1').name)).map(r=>[r.name,!!r.own]))"))
    pg.evaluate("A.addWalk(30)"); print('walk toast:', pg.evaluate("document.querySelector('#toast span').textContent"))
    print('praise:', pg.evaluate("praise(todayISO()).map(p=>p.text)"))
    print('ics len:', pg.evaluate("(()=>{let n=0;const o=downloadBlob;window.downloadBlob=(b)=>{n=b.size};A.exportIcs();window.downloadBlob=o;return n})()"))
    # cheat na dnešek: plán večerní hříchy a pohyb, který je pokryje
    pg.evaluate("App.date=todayISO();go('dnes')"); pg.wait_for_timeout(200)
    pg.evaluate("(()=>{const d=getDay(App.date);d.beers=0;d.fried_g=0;d.cheat_items=[];saveDay(d)})()")
    zaklad = pg.evaluate("calcDay(S(),Foods(),Recipes(),effectiveDay(App.date),currentWeight()).base.planWalk")
    pg.evaluate("A.dayField('beers','2','Piva')"); pg.wait_for_timeout(200)
    b2 = pg.evaluate("(()=>{const b=calcDay(S(),Foods(),Recipes(),effectiveDay(App.date),currentWeight()).base;return {cheat:Math.round(b.cheatKcal),chuze:b.planWalk,pokryto:Math.round(b.cheatCovered),zbyva:Math.round(b.cheatRest)}})()")
    print('2 piva:', b2, '· cíl chůze byl', zaklad)
    # výběr ze seznamu s hledáním
    pg.evaluate("openCheatPicker()"); pg.wait_for_timeout(300)
    pg.fill('#chq', 'řízek'); pg.wait_for_timeout(250)
    print('hledání řízek najde:', pg.evaluate("document.querySelectorAll('.modal .pitem').length"))
    pg.evaluate("document.querySelector('.modal .pitem').click()"); pg.wait_for_timeout(300)
    pg.evaluate("openCheatPicker()"); pg.wait_for_timeout(250)
    pg.fill('#chq', 'hranolky'); pg.wait_for_timeout(250)
    pg.evaluate("document.querySelector('.modal .pitem').click()"); pg.wait_for_timeout(300)
    print('po textu:', pg.evaluate("effectiveDay(App.date).cheat_items.map(i=>i.food+':'+i.kcal)"))
    b3 = pg.evaluate("(()=>{const b=calcDay(S(),Foods(),Recipes(),effectiveDay(App.date),currentWeight()).base;return {cheat:Math.round(b.cheatKcal),chuze:b.planWalk,zbyva:Math.round(b.cheatRest)}})()")
    print('s řízkem a hranolkami:', b3)
    pg.evaluate("openCheatPicker()"); pg.wait_for_timeout(250)
    pg.fill('#chvl', 'něco divného'); pg.evaluate("window._chvl()"); pg.wait_for_timeout(250)
    print('neznámé otevře odhad:', pg.evaluate("!!document.querySelector('#cheat-k')"))
    pg.click('#ckok'); pg.wait_for_timeout(250)
    print('po ručním odhadu:', pg.evaluate("effectiveDay(App.date).cheat_items.length"), 'položek')
    pg.evaluate("A.cheatDel(0)"); pg.wait_for_timeout(200)
    print('po odebrání:', pg.evaluate("effectiveDay(App.date).cheat_items.length"), 'položek')
    pg.evaluate("(()=>{const d=getDay(App.date);d.beers=0;d.fried_g=0;d.cheat_items=[];saveDay(d)})()")
    # PIN
    pg.evaluate("Store.profile=null;LS.del('profile');render()"); pg.fill('#lem','r.pesek24@gmail.com'); pg.fill('#lpw','spatne'); pg.click('#lbtn'); pg.wait_for_timeout(100); print('login wrong:', pg.inner_text('#lerr'))
    pg.fill('#lem','rehor.rudolf@gmail.com'); pg.fill('#lpw','06392'); pg.click('#lbtn'); pg.wait_for_timeout(200); print('coach login role:', pg.evaluate("Store.profile.role"), pg.evaluate("App.view"))
    # Trénink: Robertův týden, den v listu, uložení „každé X“ nebo „jen tento den“
    pg.evaluate("window.TPL=()=>activePlanFor(addDays(todayISO(),14));go('trenink');A.trDaySheet(addDays(mondayOf(todayISO()),7))"); pg.wait_for_timeout(100)
    pg.evaluate("A.trAdd('Dřep');A.trAdd('Kettlebell swing');A.trAdd('Běh pomalý');A.trDraftField('walk_min',45);A.trSave();document.querySelector('#cy')&&document.querySelector('#cy').click()"); pg.wait_for_timeout(150)
    print('šablona platí od upraveného dne:', pg.evaluate("TPL()&&TPL().active_from===addDays(mondayOf(todayISO()),7)"), '· po:', pg.evaluate("TPL().days[0].items.map(i=>i.ex).join(', ')+' / '+TPL().days[0].walk_min+' min'"))
    # knihovna cviků: nový, oblíbený, hledání, přejmenování, smazání
    pg.evaluate("A.exEdit(null)"); pg.fill('#exn','Testovací cvik'); pg.fill('#exr','15'); pg.click('#exok'); pg.wait_for_timeout(150)
    print('nový cvik:', pg.evaluate("Exercises().filter(e=>!e.seed).map(e=>e.ex+':'+e.reps)"))
    print('hledání:', pg.evaluate("Exercises().filter(e=>e.ex.toLowerCase().includes('testovac')).length"), 'z', pg.evaluate("Exercises().length"))
    pg.evaluate("A.exFav('testovaci-cvik')"); print('oblíbené:', pg.evaluate("exFavs()"))
    pg.evaluate("A.exEdit('testovaci-cvik')"); pg.fill('#exn','Testovací cvik 2'); pg.click('#exok'); pg.wait_for_timeout(150)
    print('po přejmenování:', pg.evaluate("Exercises().filter(e=>!e.seed).map(e=>e.ex)"))
    pg.evaluate("A.trDaySheet(addDays(mondayOf(todayISO()),7));A.trAdd('Testovací cvik 2');A.trSave();document.querySelector('#cy')&&document.querySelector('#cy').click()"); print('v plánu:', pg.evaluate("TPL().days[0].items.map(i=>i.ex)"))
    pg.evaluate("A.exEdit('testovaci-cvik-2')"); pg.click('#exdel'); pg.wait_for_timeout(100); pg.click('.modal #cy'); pg.wait_for_timeout(150)
    print('po smazání zbývá vlastních:', pg.evaluate("Exercises().filter(e=>!e.seed).length"))
    # uložené tréninky: uložit den, najít, vložit do jiného dne, upravit, smazat
    pg.evaluate("A.twEdit(null,{name:'Pondělí – trénink',items:JSON.parse(JSON.stringify(TPL().days[0].items))})"); pg.wait_for_timeout(150); pg.click('#twok'); pg.wait_for_timeout(200)
    print('uložené tréninky:', pg.evaluate("Workouts().map(w=>w.name+':'+w.items.length)"))
    print('hledání podle cviku:', pg.evaluate("Workouts().filter(w=>w.items.some(i=>i.ex==='Dřep')).length"))
    pg.evaluate("A.trDaySheet(addDays(mondayOf(todayISO()),9));App.trDraft.items=JSON.parse(JSON.stringify(Workouts()[0].items));A.trSave();document.querySelector('#cy')&&document.querySelector('#cy').click()")
    print('vloženo do středy:', pg.evaluate("TPL().days[2].items.map(i=>i.ex)"))
    pg.evaluate("A.twEdit(Workouts()[0].id)"); pg.wait_for_timeout(150); pg.fill('#twn','Testovací trénink'); pg.evaluate("window._twdel(0)"); pg.wait_for_timeout(100); pg.click('#twok'); pg.wait_for_timeout(200)
    print('po úpravě:', pg.evaluate("Workouts().map(w=>w.name+':'+w.items.length)"))
    pg.evaluate("A.twEdit(Workouts()[0].id)"); pg.wait_for_timeout(150); pg.click('#twdel'); pg.wait_for_timeout(100); pg.click('.modal #cy'); pg.wait_for_timeout(200)
    print('po smazání tréninků:', pg.evaluate("Workouts().length"))
    # výjimka jen na jeden den nemění šablonu
    pg.evaluate("A.trDaySheet(addDays(mondayOf(todayISO()),11));A.trScope('day');A.trDraftField('walk_min',90);A.trSave();document.querySelector('#cy')&&document.querySelector('#cy').click()")
    print('výjimka pátek:', pg.evaluate("dayActivityPlan(addDays(mondayOf(todayISO()),11)).source+' '+dayActivityPlan(addDays(mondayOf(todayISO()),11)).walk_min+' min · šablona '+TPL().days[4].walk_min+' min'"))
    # změna šablony nesmí přepsat minulé dny: posunout šablonu do minula a upravit dnešní den
    pg.evaluate("(()=>{const pl=TPL();pl.active_from=addDays(mondayOf(todayISO()),-7);saveTrainingPlan(pl)})()")
    past = pg.evaluate("dayActivityPlan(addDays(todayISO(),-7)).items.length")
    pg.evaluate("A.trDaySheet(todayISO());A.trAdd('Most (glute bridge)');A.trSave();document.querySelector('#cy')&&document.querySelector('#cy').click()")
    print('verze: minulý týden', past, '→', pg.evaluate("dayActivityPlan(addDays(todayISO(),-7)).items.length"), '· dnes', pg.evaluate("dayActivityPlan(todayISO()).items.length"), '· verzí', pg.evaluate("trainingPlans().length"))
    pg.evaluate("(()=>{const vse=trainingPlans();const d=todayISO();vse.forEach(p=>{if(p.active_from===d)Store.remove('training',p.id)});const pl=trTemplate();pl.active_from=mondayOf(d);saveTrainingPlan(pl)})()")
    print('plan:', pg.evaluate("(()=>{const p=trTemplate();return p.name+' d0 items='+p.days[0].items.length+' kcal='+Math.round(sessionKcal(p.days[0].items,currentWeight()))+' active='+p.active_from})()"))
    print('client act:', pg.evaluate("(()=>{localLogin('client');const d=effectiveDay(mondayOf(todayISO()));const c=calcDay(S(),Foods(),Recipes(),d,currentWeight());return JSON.stringify({planWalk:d.act.planWalk,planKcal:Math.round(d.act.planKcal),planLimit:Math.round(c.base.planLimit),maxIntake:Math.round(c.base.maxIntake),bmr:Math.round(c.base.bmr),belowBmr:c.base.belowBmr,tasks:dayTasks(mondayOf(todayISO())).map(t=>t.id).join(',')})})()"))
    pg.evaluate("App.date=mondayOf(todayISO());go('dnes');A.trainDoneAll()"); print('after training done:', pg.evaluate("(()=>{const c=calcDay(S(),Foods(),Recipes(),effectiveDay(App.date),currentWeight());return 'doneKcal='+Math.round(c.base.doneKcal)+' maxIntake='+Math.round(c.base.maxIntake)})()"))
    # cvičení: série, pauza mezi sériemi, zápis skutečnosti, souhrn
    pg.evaluate("App.date=mondayOf(todayISO());go('dnes')"); pg.wait_for_timeout(150)
    pg.evaluate("(()=>{const d=getDay(App.date);d.training={done:{}};saveDay(d)})()")
    print('plán na den:', pg.evaluate("((effectiveDay(App.date).act||{}).items||[]).map(i=>i.ex+':'+(i.sets||'-'))"))
    pg.evaluate("A.trRun(0)"); pg.wait_for_timeout(200)
    pg.fill('#trreps', '10'); pg.fill('#trkg', '20'); pg.evaluate("A.trSetDone(0,0)"); pg.wait_for_timeout(200)
    print('pauza běží:', pg.evaluate("!!(App.tr && App.tr.rest)"), '· zbývá s:', pg.evaluate("App.tr.rest?Math.round((App.tr.rest.end-Date.now())/1000):0"))
    pg.evaluate("A.trRestPlus(30)"); print('po +30 s zbývá:', pg.evaluate("Math.round((App.tr.rest.end-Date.now())/1000)"))
    pg.evaluate("A.trRestEnd()"); pg.wait_for_timeout(150)
    print('pauza ukončena dřív:', pg.evaluate("!(App.tr && App.tr.rest)"))
    pg.fill('#trreps', '8'); pg.fill('#trkg', '20'); pg.evaluate("A.trSetDone(0,1)"); pg.wait_for_timeout(200)
    pg.evaluate("A.trRestEnd()"); pg.wait_for_timeout(100)
    print('rekordy:', pg.evaluate("JSON.stringify((App.tr&&App.tr.prs||[]).map(p=>p.ex+': '+p.what.join(', ')))"))
    pg.evaluate("A.trSetDone(0,2)"); pg.wait_for_timeout(200); pg.evaluate("A.trRestEnd()"); pg.wait_for_timeout(100)
    print('po třetí sérii hotovo:', pg.evaluate("!!trState(App.date).done[0]"))
    pg.evaluate("A.trAddSet(0)"); pg.wait_for_timeout(150)
    pg.fill('#trreps', '6'); pg.fill('#trkg', '30'); pg.evaluate("A.trSetDone(0,3)"); pg.wait_for_timeout(200); pg.evaluate("A.trRestEnd()"); pg.wait_for_timeout(100)
    print('série navíc:', pg.evaluate("trSets(App.date,0).filter(Boolean).length"), '· cvik zůstal hotový:', pg.evaluate("!!trState(App.date).done[0]"))
    pg.evaluate("A.trGo(2)"); print('vlastní pořadí – skok na cvik:', pg.evaluate("App.tr.i"))
    pg.evaluate("A.trGo(0)")
    print('zapsané série:', pg.evaluate("JSON.stringify(trSets(App.date,0).map(x=>x&&x.reps+'x'+x.kg))"))
    pg.evaluate("A.trFinish()"); pg.wait_for_timeout(250)
    print('souhrn:', pg.evaluate("document.querySelector('.modal .praise div div').textContent"), '·', pg.evaluate("[...document.querySelectorAll('.modal .stats3 b')].map(b=>b.textContent.trim()).join(' | ')"))
    pg.click('#trrpe .chip >> nth=2'); pg.click('#trfeel .chip >> nth=1')
    pg.click('#trsave'); pg.wait_for_timeout(250)
    print('zápis tréninku:', pg.evaluate("JSON.stringify({rpe:getDay(App.date).training.rpe,feel:getDay(App.date).training.feel,serii:(getDay(App.date).training.log[0]||{sets:[]}).sets.length})"))
    print('bmr floor test:', pg.evaluate("(()=>{const s=S();const b=calcBase(s,132.8,0,0,5,0,0,{planWalk:0,planKcal:0,doneKcal:0});return JSON.stringify({raw:Math.round(b.totalOut-b.deficit),maxIntake:Math.round(b.maxIntake),bmr:Math.round(b.bmr),belowBmr:b.belowBmr,walkToBmr:b.walkToBmr})})()"))
    print('measure:', pg.evaluate("[measureText('Rýže vařená',150), measureText('Chléb konzumní (Šumava)',100), measureText('Vejce',120), measureText('Zelenina míchaná',150), measureText('Kuřecí prsa',150)]"))
    pg.evaluate("generateWeek(App.week,'all')"); print('routine:', pg.evaluate("(()=>{const wk=getWeek(App.week);return new Set(wk.plan.map(d=>d[0])).size+' snídaní, '+new Set(wk.plan.map(d=>d[2])).size+' svačin'})()"))
    # mismatch after training change
    pg.evaluate("localLogin('coach')"); pg.evaluate("go('trenink');A.trDaySheet(todayISO());A.trAdd('Běh pomalý');A.trItem(App.trDraft.items.length-1,'min',60);A.trSave();document.querySelector('#cy')&&document.querySelector('#cy').click()"); pg.wait_for_timeout(100)
    print('pace:', pg.evaluate("(()=>{const p=paceOverview();return JSON.stringify({target:+p.target.toFixed(2),proj:+p.projThis.toFixed(2),floor:p.floorThis.length,actual:p.actual})})()"))
    print('měsíc tréninku:', pg.evaluate("document.querySelectorAll('#main .tmd2').length"), 'dní ·', pg.evaluate("(document.querySelector('#main .sumr')||{}).textContent"))
    pg.evaluate("localLogin('client')"); print('mismatch today:', pg.evaluate("JSON.stringify(dayMismatch(todayISO()))"))
    pg.evaluate("A.fitDay(todayISO())"); print('after fit:', pg.evaluate("JSON.stringify(dayMismatch(todayISO()))"), pg.evaluate("(()=>{const w=currentWeight();const r=calcPlanDay(S(),Foods(),Recipes(),getWeek(App.week).plan[dayIndex(todayISO())],w,planActFor(todayISO(),w));return r.kcal.toFixed(0)+'/'+r.planLimit.toFixed(0)})()"))
    pg.evaluate("localLogin('coach')")
    pg.evaluate("go('klient')"); print('týden v číslech:', pg.evaluate("(()=>{const R=weekReport(mondayOf(todayISO()));return R.weigh+'/'+R.past+' vážení, '+R.okN+' OK'})()"), '· tlačítko zprávy:', pg.evaluate("!!document.querySelector('[onclick*=copyReport]')"))
    print('verdikt:', pg.evaluate("document.querySelector('#main .chip2').textContent"), '· k řešení:', pg.evaluate("document.querySelectorAll('#main .td').length"))
    print('Robert bez vzkazů:', pg.evaluate("!document.querySelector('#cmsg') && !/Vzkaz/.test(document.querySelector('#main').innerText)"))
    print('paceGuard:', pg.evaluate("paceGuard().map(g=>g.text)"))
    pg.evaluate("go('nastaveni')"); pg.fill('#st_walk_min','70'); pg.press('#st_walk_min','Tab'); pg.wait_for_timeout(150)
    print('settings:', pg.evaluate("S().walk_min"), pg.evaluate("Store.rows('settings').map(r=>r.user_id)"), 'log:', pg.evaluate("(S().log||[]).slice(-1).map(l=>l.k+':'+l.from+'→'+l.to)"))
    pg.fill('#st_steps_goal','8000'); pg.press('#st_steps_goal','Tab'); pg.wait_for_timeout(150)
    print('kroky → faktor:', pg.evaluate("S().steps_goal+' / '+S().activity"))
    pg.evaluate("A.applyAdvice(JSON.stringify({protein_min:175}))"); print('doporučení v historii:', pg.evaluate("(S().log||[]).some(l=>l.k==='protein_min')"))
    pg.evaluate("A.editFood('f1')"); pg.fill('#fn','Hovězí přední TEST'); pg.click('#fsave'); pg.wait_for_timeout(100)
    print('food renamed:', pg.evaluate("Foods().find(f=>f.id==='f1').name"), 'recipes using:', pg.evaluate("Recipes().filter(r=>r.items.some(i=>i.food==='Hovězí přední TEST')).length"))
    pg.evaluate("A.seedAll()"); pg.click('.modal #cy'); pg.wait_for_timeout(300)
    print('seeded foods rows:', pg.evaluate("Store.db.foods.length"), 'f1 name after seed:', pg.evaluate("Foods().find(f=>f.id==='f1').name"))
    # ro mode
    print('pohled Roberta v menu:', pg.evaluate("MORE_COACH.some(x=>x[0]==='__preview')"))
    _pr = pg.evaluate("(()=>{const r=perRange();const a=diagnoza().list, b=diagnoza(r.from,r.to).list;return [a.length+b.length, [...a,...b].every(x=>x.title && x.em)]})()")
    print('problémy mají nadpis a ikonu:', _pr[1], '·', _pr[0])
    if not _pr[1]: errs.append('problém bez nadpisu')
    print('trenér bez databáze a plánování jídel:', pg.evaluate("!NAV_COACH.some(x=>x[0]==='databaze') && typeof A.toggleCoachPlan==='undefined'"), '· go(databaze) →', pg.evaluate("(go('databaze'),App.view)"))
    # reload persistence
    pg.reload(); pg.wait_for_timeout(300); print('after reload profile:', pg.evaluate("Store.profile && Store.profile.role"), 'meas:', pg.evaluate("Store.db.measurements.length"))
    # rozbor váhy přes všechny větve včetně „zbytku“: 35 dní vážení, 16 potvrzených dnů s chůzí, kroky, pivy
    z=b.new_page(); z.on('pageerror', lambda e: errs.append('rozbor: '+str(e))); z.goto(URL); z.wait_for_timeout(200)
    z.evaluate("""localLogin("client"); const s=S(); s.start_date=addDays(todayISO(),-35); s.start_weight=134.4; saveSettings(s);
      for(let k=35;k>=1;k--){ const dt=addDays(todayISO(),-k); saveMeas({date:dt, weight: Math.round((134.4-(35-k)*0.01+(k%3)*0.3)*10)/10});
        if(k<=16){ const d=getDay(dt); d.walk_min=k%2?25:60; d.beers=k%7===2?6:0; d.steps=4500+(k%3)*500; S().courses.forEach(c=>{d.meals[c.key]={sel:'Kuřecí rizoto se zeleninou a sýrem',eaten:true}}); d.reviewed=true; saveDay(d);} }""")
    _w = z.evaluate("(()=>{const W=weightWhy(addDays(todayISO(),-15),addDays(todayISO(),-1)); const D=diagnoza(); return [W.state, W.causes.map(c=>c.key).join(','), D.list.length]})()")
    print('rozbor váhy (14 dní):', _w)
    if 'zbytek' not in _w[1]: errs.append('rozbor: chybí větev zbytek')
    _g = z.evaluate("(()=>{const g=goalCheck(); const s=S(); s.goal_date=addDays(todayISO(),300); saveSettings(s); const h=goalCheck(); const r1=simGoal(0.5,1,true,130,todayISO()), r2=simGoal(1,1,true,130,todayISO()); return [!!g, h.req, r1>r2, !!goalSignal()]})()")
    print('dosažitelnost cíle:', _g)
    if not _g[0] or _g[2] is not True: errs.append('cíl: goalCheck/simGoal nefunguje')
    z.close()
    # šablona „každé X“ platí od upravovaného dne, minulé dny a nastavení zpětně nemění (6. 10. 2026)
    y=b.new_page(); y.on('pageerror', lambda e: errs.append('retro: '+str(e))); y.goto(URL); y.wait_for_timeout(200)
    y.evaluate("localStorage.clear()"); y.goto(URL); y.wait_for_timeout(200); y.evaluate("localLogin('coach');render()")
    def trsave(off, w):
        y.evaluate(f"A.trDaySheet(addDays(todayISO(),{off}))"); y.wait_for_timeout(100)
        y.evaluate(f"App.trDraft.walk_min={w};App.trDraft.scope='every';A.trSave()"); y.wait_for_timeout(100); y.click('#cy'); y.wait_for_timeout(100)
    wq="[-7,0,7,14].map(o=>dayActivityPlan(addDays(todayISO(),o)).walk_min).join(',')"
    trsave(7, 90); r1=y.evaluate(wq); trsave(0, 45); r2=y.evaluate(wq)
    print('šablona od dne:', r1, '|', r2)
    if r1!='60,60,90,90' or r2!='60,45,45,45': errs.append('retro: šablona mění dny před upravovaným dnem')
    y.evaluate("const s=S(); s.log=[]; saveSettings(s)"); lim="Math.round(calcDay(S(),Foods(),Recipes(),effectiveDay(addDays(todayISO(),-3)),130).base.planLimit)"
    l1=y.evaluate(lim); y.evaluate("A.setSetting('rate_pct','1.1')"); l2=y.evaluate(lim)
    print('minulý den po změně tempa:', l1, l2)
    if l1!=l2: errs.append('retro: změna tempa přepočítala minulý den')
    y.evaluate("go('historie')"); n=y.evaluate("document.querySelectorAll('#main .li').length"); y.evaluate("A.histRevert(histRows()[0].id)"); y.click('#cy'); y.wait_for_timeout(100)
    print('historie:', n, 'záznamů · tempo po vrácení', y.evaluate("S().rate_pct"))
    if n<3 or y.evaluate("S().rate_pct")==1.1: errs.append('historie: vrácení nefunguje')
    y.evaluate("A.trDaySheet(addDays(todayISO(),21))"); y.wait_for_timeout(100); y.evaluate("A.trDraftField('walk_min','900')")
    print('chůze 900 → ', y.evaluate("App.trDraft.walk_min"), '· potvrzení:', y.evaluate("!!document.querySelector('#cy')"))
    if y.evaluate("App.trDraft.walk_min")!=240: errs.append('meze: plán chůze nad 240')
    y.close()
    print('errors:', errs or 'none'); b.close()
