from playwright.sync_api import sync_playwright
import os; URL='file://'+os.path.abspath(os.path.join(os.path.dirname(__file__),'..','out','index.html'))
with sync_playwright() as p:
    b=p.chromium.launch(); pg=b.new_page(viewport={'width':1440,'height':900},locale='cs-CZ',timezone_id='Europe/Prague'); errs=[]
    pg.on('pageerror', lambda e: errs.append(str(e))); pg.route('**/fonts.googleapis.com/**', lambda r: r.abort())
    pg.goto(URL); pg.wait_for_timeout(200)
    pg.evaluate('localLogin("client")')
    # měření – uložit dnešní váhu přes UI
    pg.evaluate("A.mereni('zapis')"); pg.fill('#m_weight','131.9'); pg.fill('#m_waist','119'); pg.click('text=Uložit zápis'); pg.wait_for_timeout(100)
    print('meas saved:', pg.evaluate("Meas().length"), pg.evaluate("Meas()[0]"))
    # týden – vybrat snídani přes UI select v pondělí
    pg.evaluate("go('tyden')"); pg.evaluate("A.planSel(0,0,'Tvarohová mísa s ovocem a oříšky')"); pg.wait_for_timeout(100)
    print('week plan mon:', pg.evaluate("getWeek(App.week).plan[0]"))
    pg.evaluate("A.copyWeek()") ; 
    # dnes – změnit jídlo, vyměnit surovinu, upravit gramy, pátek piva
    pg.evaluate("App.date=addDays(App.week,0);go('dnes')")
    pg.evaluate("A.toggleCourse('snidane')"); pg.wait_for_timeout(100)   # jídla jsou sbalená, editace až po rozkliknutí
    pg.evaluate("document.querySelector('.course .pickbtn').click()"); pg.wait_for_timeout(100); pg.fill('#pkq','míchaná'); pg.wait_for_timeout(100); print('picker hits:', pg.evaluate("document.querySelectorAll('.pitem').length")); pg.evaluate("window._pick('Míchaná vejce se šunkou a chlebem')"); pg.wait_for_timeout(100)
    print('sel:', pg.evaluate("getDay(App.date).meals.snidane"))
    pg.click('.course >> nth=0 >> .items .pickbtn >> nth=0'); pg.wait_for_timeout(150)   # výměna suroviny přes panel s hledáním
    pg.fill('#fp-q','tofu'); pg.wait_for_timeout(150); print('panel surovin našel:', pg.evaluate("document.querySelectorAll('.pitem').length"))
    pg.evaluate("window._fppick('Tofu')"); pg.wait_for_timeout(150)
    pg.fill('.course >> nth=0 >> .items input >> nth=1','80'); pg.press('.course >> nth=0 >> .items input >> nth=1','Tab'); pg.wait_for_timeout(100)
    print('edits:', pg.evaluate("JSON.stringify(getDay(App.date).meals.snidane)"))
    print('checks text:', pg.evaluate("[...document.querySelectorAll('.checks div')].map(d=>d.textContent)"))
    pg.evaluate("A.dayField('beers','6','Piva')"); pg.wait_for_timeout(100)
    print('friday hero:', pg.evaluate("document.querySelector('.herob .big').textContent"), pg.evaluate("(()=>{const c=document.querySelector('.checks .chk');return c?c.querySelector('.tag').textContent+': '+c.querySelector('.ct').textContent.slice(0,60):'-'})()"))
    pg.evaluate("A.removeItem('snidane',0);A.extraAdd('snidane');A.extraFood('snidane',0,'Tofu');A.extraG('snidane',0,150)"); print('remove/extra:', pg.evaluate("JSON.stringify(getDay(App.date).meals.snidane)"), pg.evaluate("calcDay(S(),Foods(),Recipes(),effectiveDay(App.date),currentWeight()).courses[0].items.map(i=>i.food+':'+i.g).join(',')"))
    pg.evaluate("A.resetCourse('snidane')");
    pg.evaluate("toggleFav('Míchaná vejce se šunkou a chlebem')"); print('fav:', pg.evaluate("Prefs().favs"), 'recent:', pg.evaluate("Prefs().recent.slice(0,2)"))
    pg.evaluate("generateWeek(App.week,'all')"); print('gen week:', pg.evaluate("(()=>{const wk=getWeek(App.week);const s=S();return wk.plan.map(d=>calcPlanDay(s,Foods(),Recipes(),d,currentWeight()).status).join(' | ')+' uniq:'+new Set(wk.plan.flat()).size})()"))
    pg.evaluate("localLogin('coach');saveCoachNote('Drž pátek na 3 pivech.');localLogin('client')"); print('note visible:', pg.evaluate("go('dnes');document.querySelector('.note')?.textContent.includes('3 pivech')"))
    print('coach line:', pg.evaluate("coachLine(todayISO()).main"))
    print('plausible:', pg.evaluate("JSON.stringify(weightPlausible(121, todayISO()))"))
    pg.evaluate("A.editFood(null,'own')"); pg.fill('#fn','Moje proteinová tyčinka'); pg.fill('#fk','380'); pg.fill('#fp','30'); pg.fill('#fs','35'); pg.fill('#ff','12'); pg.click('#fsave'); pg.wait_for_timeout(100); print('own food:', pg.evaluate("Foods().filter(f=>f.own).map(f=>f.name+':'+f.kcal)"))
    print('after reset:', pg.evaluate("JSON.stringify(getDay(App.date).meals.snidane)"))
    # vlastní recept
    pg.evaluate("A.jidlo('recepty');A.editOwn()"); pg.fill('#re-n','Testovací omeleta'); pg.evaluate("window._reAdd()"); pg.wait_for_timeout(150); pg.fill('#fp-q','vejce'); pg.wait_for_timeout(100); print('food picker hits:', pg.evaluate("document.querySelectorAll('.pitem').length")); pg.evaluate("window._fppick('Vejce')"); pg.evaluate("window._reG(0,300)")
    pg.evaluate("window._reAdd()"); pg.wait_for_timeout(150); pg.evaluate("window._fppick('Chléb konzumní (Šumava)')"); pg.evaluate("window._reG(1,80)"); pg.wait_for_timeout(100)
    print('own hint:', pg.evaluate("document.querySelector('.modal .status').textContent"))
    pg.click('#re-save'); pg.wait_for_timeout(100); print('own recipes:', pg.evaluate("Recipes().filter(r=>r.own).map(r=>r.name)"), 'in menu:', pg.evaluate("recipesFor('Snídaně').some(r=>r.name==='Testovací omeleta')"))
    # export JSON obsah
    print('export keys:', pg.evaluate("(()=>{const uid=Store.ownerId();return TABLES.map(t=>t+':'+Store.db[t].filter(r=>r.user_id===uid).length)})()"))
    # coach: nastavení + editace potraviny + seed
    # úkoly, snědeno, uzavření
    pg.evaluate("App.date=todayISO();go('dnes')"); print('tasks:', pg.evaluate("dayTasks(todayISO()).map(t=>t.id+':'+(t.done?1:0)).join(' ')"))
    pg.evaluate("A.eaten('snidane',true)"); print('eaten:', pg.evaluate("getDay(todayISO()).meals.snidane.eaten"))
    pg.evaluate("A.suggestOne('obed')"); print('suggestOne:', pg.evaluate("getDay(todayISO()).meals.obed.sel"), 'toast:', pg.evaluate("document.querySelector('#toast span').textContent"))
    pg.evaluate("Undo.undo()"); print('after undo:', pg.evaluate("getDay(todayISO()).meals.obed.sel"))
    pg.evaluate("A.editFood('f1','override')"); pg.fill('#fk','999'); pg.click('#fsave'); pg.wait_for_timeout(100); print('override:', pg.evaluate("JSON.stringify(Foods().filter(f=>f.id==='f1').map(f=>[f.name,f.kcal,!!f.overridden]))"))
    pg.evaluate("A.editFood('f1','override')"); pg.click('#fdel'); pg.wait_for_timeout(100); pg.click('.modal #cy'); pg.wait_for_timeout(100); print('override removed:', pg.evaluate("Foods().find(f=>f.id==='f1').kcal"))
    pg.evaluate("A.addWalk(30)"); print('walk toast:', pg.evaluate("document.querySelector('#toast span').textContent"))
    print('praise:', pg.evaluate("praise(todayISO()).map(p=>p.text)"))
    print('ics len:', pg.evaluate("(()=>{let n=0;const o=downloadBlob;window.downloadBlob=(b)=>{n=b.size};A.exportIcs();window.downloadBlob=o;return n})()"))
    # cheat na dnešek: plán večerní hříchy a pohyb, který je pokryje
    pg.evaluate("App.date=todayISO();go('dnes')"); pg.wait_for_timeout(200)
    pg.evaluate("(()=>{const d=getDay(App.date);d.beers=0;d.fried_g=0;d.cheat_items=[];saveDay(d)})()")
    zaklad = pg.evaluate("calcDay(S(),Foods(),Recipes(),effectiveDay(App.date),currentWeight()).base.planWalk")
    pg.evaluate("A.dayField('beers','2','Piva')"); pg.wait_for_timeout(200)
    b2 = pg.evaluate("(()=>{const b=calcDay(S(),Foods(),Recipes(),effectiveDay(App.date),currentWeight()).base;return {cheat:Math.round(b.cheatKcal),chuze:b.planWalk,pokryto:Math.round(b.cheatCovered),zbyva:Math.round(b.cheatRest)}})()")
    print('2 piva:', b2, '· cíl chůze byl', zaklad)
    pg.fill('#cheat-q', 'řízek a hranolky'); pg.evaluate("A.cheatAdd()"); pg.wait_for_timeout(300)
    print('po textu:', pg.evaluate("effectiveDay(App.date).cheat_items.map(i=>i.food+':'+i.kcal)"))
    b3 = pg.evaluate("(()=>{const b=calcDay(S(),Foods(),Recipes(),effectiveDay(App.date),currentWeight()).base;return {cheat:Math.round(b.cheatKcal),chuze:b.planWalk,zbyva:Math.round(b.cheatRest)}})()")
    print('s řízkem a hranolkami:', b3)
    pg.fill('#cheat-q', 'něco divného'); pg.evaluate("A.cheatAdd()"); pg.wait_for_timeout(250)
    print('neznámé otevře odhad:', pg.evaluate("!!document.querySelector('#cheat-k')"))
    pg.click('#ckok'); pg.wait_for_timeout(250)
    print('po ručním odhadu:', pg.evaluate("effectiveDay(App.date).cheat_items.length"), 'položek')
    pg.evaluate("A.cheatDel(0)"); pg.wait_for_timeout(200)
    print('po odebrání:', pg.evaluate("effectiveDay(App.date).cheat_items.length"), 'položek')
    pg.evaluate("(()=>{const d=getDay(App.date);d.beers=0;d.fried_g=0;d.cheat_items=[];saveDay(d)})()")
    # PIN
    pg.evaluate("Store.profile=null;LS.del('profile');render()"); pg.fill('#lem','r.pesek24@gmail.com'); pg.fill('#lpw','spatne'); pg.click('#lbtn'); pg.wait_for_timeout(100); print('login wrong:', pg.inner_text('#lerr'))
    pg.fill('#lem','rehor.rudolf@gmail.com'); pg.fill('#lpw','06392'); pg.click('#lbtn'); pg.wait_for_timeout(200); print('coach login role:', pg.evaluate("Store.profile.role"), pg.evaluate("App.view"))
    pg.evaluate("go('trenink');A.tpNew()"); pg.evaluate("App.tpDay=0;A.tpItemAdd('Dřep');A.tpItemAdd('Kettlebell swing');A.tpItemAdd('Běh pomalý')")
    # knihovna cviků: nový, oblíbený, hledání, přejmenování, smazání
    pg.evaluate("A.exEdit(null)"); pg.fill('#exn','Testovací cvik'); pg.fill('#exr','15'); pg.click('#exok'); pg.wait_for_timeout(150)
    print('nový cvik:', pg.evaluate("Exercises().filter(e=>!e.seed).map(e=>e.ex+':'+e.reps)"))
    print('hledání:', pg.evaluate("Exercises().filter(e=>e.ex.toLowerCase().includes('testovac')).length"), 'z', pg.evaluate("Exercises().length"))
    pg.evaluate("A.exFav('testovaci-cvik')"); print('oblíbené:', pg.evaluate("exFavs()"))
    pg.evaluate("A.exEdit('testovaci-cvik')"); pg.fill('#exn','Testovací cvik 2'); pg.click('#exok'); pg.wait_for_timeout(150)
    print('po přejmenování:', pg.evaluate("Exercises().filter(e=>!e.seed).map(e=>e.ex)"))
    pg.evaluate("A.tpItemAdd('Testovací cvik 2')"); print('v plánu:', pg.evaluate("trainingPlans().find(p=>p.id===App.tpId).days[0].items.map(i=>i.ex)"))
    pg.evaluate("A.exEdit('testovaci-cvik-2')"); pg.click('#exdel'); pg.wait_for_timeout(100); pg.click('.modal #cy'); pg.wait_for_timeout(150)
    print('po smazání zbývá vlastních:', pg.evaluate("Exercises().filter(e=>!e.seed).length"))
    # uložené tréninky: uložit den, najít, vložit do jiného dne, upravit, smazat
    pg.evaluate("A.twSaveDay()"); pg.wait_for_timeout(150); pg.click('#twok'); pg.wait_for_timeout(200)
    print('uložené tréninky:', pg.evaluate("Workouts().map(w=>w.name+':'+w.items.length)"))
    print('hledání podle cviku:', pg.evaluate("Workouts().filter(w=>w.items.some(i=>i.ex==='Dřep')).length"))
    pg.evaluate("App.tpDay=2;render()"); pg.evaluate("(()=>{const w=Workouts()[0];const pl=trainingPlans().find(p=>p.id===App.tpId);pl.days[2].items=JSON.parse(JSON.stringify(w.items));saveTrainingPlan(pl)})()")
    print('vloženo do středy:', pg.evaluate("trainingPlans().find(p=>p.id===App.tpId).days[2].items.map(i=>i.ex)"))
    pg.evaluate("A.twEdit(Workouts()[0].id)"); pg.wait_for_timeout(150); pg.fill('#twn','Testovací trénink'); pg.evaluate("window._twdel(0)"); pg.wait_for_timeout(100); pg.click('#twok'); pg.wait_for_timeout(200)
    print('po úpravě:', pg.evaluate("Workouts().map(w=>w.name+':'+w.items.length)"))
    pg.evaluate("A.twEdit(Workouts()[0].id)"); pg.wait_for_timeout(150); pg.click('#twdel'); pg.wait_for_timeout(100); pg.click('.modal #cy'); pg.wait_for_timeout(200)
    print('po smazání tréninků:', pg.evaluate("Workouts().length"))
    pg.evaluate("App.tpDay=0;render()")
    pg.evaluate("A.tpDayField('walk_min',45)"); pg.evaluate("A.tpField('active_from',mondayOf(todayISO()))"); pg.wait_for_timeout(100)
    print('plan:', pg.evaluate("(()=>{const p=trainingPlans()[0];return p.name+' d0 items='+p.days[0].items.length+' kcal='+Math.round(sessionKcal(p.days[0].items,currentWeight()))+' active='+p.active_from})()"))
    print('client act:', pg.evaluate("(()=>{localLogin('client');const d=effectiveDay(mondayOf(todayISO()));const c=calcDay(S(),Foods(),Recipes(),d,currentWeight());return JSON.stringify({planWalk:d.act.planWalk,planKcal:Math.round(d.act.planKcal),planLimit:Math.round(c.base.planLimit),maxIntake:Math.round(c.base.maxIntake),bmr:Math.round(c.base.bmr),belowBmr:c.base.belowBmr,tasks:dayTasks(mondayOf(todayISO())).map(t=>t.id).join(',')})})()"))
    pg.evaluate("App.date=mondayOf(todayISO());go('dnes');A.trainDoneAll()"); print('after training done:', pg.evaluate("(()=>{const c=calcDay(S(),Foods(),Recipes(),effectiveDay(App.date),currentWeight());return 'doneKcal='+Math.round(c.base.doneKcal)+' maxIntake='+Math.round(c.base.maxIntake)})()"))
    # cvičení: série, pauza mezi sériemi, zápis skutečnosti, souhrn
    pg.evaluate("App.date=mondayOf(todayISO());go('dnes')"); pg.wait_for_timeout(150)
    pg.evaluate("(()=>{const d=getDay(App.date);d.training={done:{}};saveDay(d)})()")
    print('plán na den:', pg.evaluate("((effectiveDay(App.date).act||{}).items||[]).map(i=>i.ex+':'+(i.sets||'-'))"))
    pg.evaluate("A.trRun(0)"); pg.wait_for_timeout(200)
    pg.fill('#trreps', '10'); pg.fill('#trkg', '20'); pg.evaluate("A.trSetDone(0,0)"); pg.wait_for_timeout(200)
    print('pauza běží:', pg.evaluate("!!(App.tr && App.tr.rest)"), '· zbývá s:', pg.evaluate("App.tr.rest?Math.round((App.tr.rest.end-Date.now())/1000):0"))
    pg.evaluate("A.trRestPlus(30)"); print('po +30 s zbývá:', pg.evaluate("Math.round((App.tr.rest.end-Date.now())/1000)"))
    pg.evaluate("A.trRestEnd()"); pg.wait_for_timeout(150)
    print('pauza ukončena dřív:', pg.evaluate("!(App.tr && App.tr.rest)"))
    pg.fill('#trreps', '8'); pg.fill('#trkg', '20'); pg.evaluate("A.trSetDone(0,1)"); pg.wait_for_timeout(200)
    pg.evaluate("A.trRestEnd()"); pg.wait_for_timeout(100)
    print('rekordy:', pg.evaluate("JSON.stringify((App.tr&&App.tr.prs||[]).map(p=>p.ex+': '+p.what.join(', ')))"))
    pg.evaluate("A.trSetDone(0,2)"); pg.wait_for_timeout(200); pg.evaluate("A.trRestEnd()"); pg.wait_for_timeout(100)
    print('po třetí sérii hotovo:', pg.evaluate("!!trState(App.date).done[0]"))
    pg.evaluate("A.trAddSet(0)"); pg.wait_for_timeout(150)
    pg.fill('#trreps', '6'); pg.fill('#trkg', '30'); pg.evaluate("A.trSetDone(0,3)"); pg.wait_for_timeout(200); pg.evaluate("A.trRestEnd()"); pg.wait_for_timeout(100)
    print('série navíc:', pg.evaluate("trSets(App.date,0).filter(Boolean).length"), '· cvik zůstal hotový:', pg.evaluate("!!trState(App.date).done[0]"))
    pg.evaluate("A.trGo(2)"); print('vlastní pořadí – skok na cvik:', pg.evaluate("App.tr.i"))
    pg.evaluate("A.trGo(0)")
    print('zapsané série:', pg.evaluate("JSON.stringify(trSets(App.date,0).map(x=>x&&x.reps+'x'+x.kg))"))
    pg.evaluate("A.trFinish()"); pg.wait_for_timeout(250)
    print('souhrn:', pg.evaluate("document.querySelector('.modal .praise div div').textContent"), '·', pg.evaluate("[...document.querySelectorAll('.modal .stats3 b')].map(b=>b.textContent.trim()).join(' | ')"))
    pg.click('#trrpe .chip >> nth=2'); pg.click('#trfeel .chip >> nth=1'); pg.fill('#trnote', 'koleno v pohodě')
    pg.click('#trsave'); pg.wait_for_timeout(250)
    print('zápis tréninku:', pg.evaluate("JSON.stringify({rpe:getDay(App.date).training.rpe,feel:getDay(App.date).training.feel,note:getDay(App.date).training.note,serii:(getDay(App.date).training.log[0]||{sets:[]}).sets.length})"))
    print('bmr floor test:', pg.evaluate("(()=>{const s=S();const b=calcBase(s,132.8,0,0,5,0,0,{planWalk:0,planKcal:0,doneKcal:0});return JSON.stringify({raw:Math.round(b.totalOut-b.deficit),maxIntake:Math.round(b.maxIntake),bmr:Math.round(b.bmr),belowBmr:b.belowBmr,walkToBmr:b.walkToBmr})})()"))
    print('measure:', pg.evaluate("[measureText('Rýže vařená',150), measureText('Chléb konzumní (Šumava)',100), measureText('Vejce',120), measureText('Zelenina míchaná',150), measureText('Kuřecí prsa',150)]"))
    print('parse:', pg.evaluate("parseAteText('2 rohlíky se šunkou a sýrem eidam, jablko a jogurt').map(f=>f.name)"))
    pg.evaluate("A.saveNote(todayISO(),'bolelo koleno')"); print('note:', pg.evaluate("getDay(todayISO()).note"))
    pg.evaluate("generateWeek(App.week,'all')"); print('routine:', pg.evaluate("(()=>{const wk=getWeek(App.week);return new Set(wk.plan.map(d=>d[0])).size+' snídaní, '+new Set(wk.plan.map(d=>d[2])).size+' svačin'})()"))
    # mismatch after training change
    pg.evaluate("localLogin('coach')"); pg.evaluate("go('trenink');App.tpDay=dayIndex(todayISO());render();A.tpItemAdd('Běh pomalý');A.tpItem(document.querySelectorAll('.items tr,table.small tr').length?0:0,'min',60)"); pg.wait_for_timeout(100)
    print('pace:', pg.evaluate("(()=>{const p=paceOverview();return JSON.stringify({target:+p.target.toFixed(2),proj:+p.projThis.toFixed(2),floor:p.floorThis.length,actual:p.actual})})()"))
    print('foodbox:', pg.evaluate("document.querry===undefined?[...document.querySelectorAll('.foodbox span')].map(s=>s.textContent).join(' | '):''"))
    pg.evaluate("localLogin('client')"); print('mismatch today:', pg.evaluate("JSON.stringify(dayMismatch(todayISO()))"))
    pg.evaluate("A.fitDay(todayISO())"); print('after fit:', pg.evaluate("JSON.stringify(dayMismatch(todayISO()))"), pg.evaluate("(()=>{const w=currentWeight();const r=calcPlanDay(S(),Foods(),Recipes(),getWeek(App.week).plan[dayIndex(todayISO())],w,planActFor(todayISO(),w));return r.kcal.toFixed(0)+'/'+r.planLimit.toFixed(0)})()"))
    pg.evaluate("localLogin('coach')"); pg.evaluate("A.saveReply(todayISO(),'Odpočiň si, běh nahraď chůzí')"); print('reply:', pg.evaluate("coachReply(todayISO()).reply"))
    pg.evaluate("go('zprava')"); print('zprava text lines:', pg.evaluate("document.querySelector('pre').textContent.split('\\n').length"))
    pg.evaluate("go('klient')"); print('quiet:', pg.evaluate("document.querySelector('.quiet .qs').textContent"), pg.evaluate("document.querySelectorAll('.qlist li').length"))
    print('paceGuard:', pg.evaluate("paceGuard().map(g=>g.text)"))
    pg.evaluate("go('nastaveni')"); pg.fill('#st_walk_min','70'); pg.click('text=Uložit nastavení'); pg.wait_for_timeout(100)
    print('settings:', pg.evaluate("S().walk_min"), pg.evaluate("Store.rows('settings').map(r=>r.user_id)"))
    pg.evaluate("go('databaze');A.editFood('f1')"); pg.fill('#fn','Hovězí přední TEST'); pg.click('#fsave'); pg.wait_for_timeout(100)
    print('food renamed:', pg.evaluate("Foods().find(f=>f.id==='f1').name"), 'recipes using:', pg.evaluate("Recipes().filter(r=>r.items.some(i=>i.food==='Hovězí přední TEST')).length"))
    pg.evaluate("A.seedAll()"); pg.click('.modal #cy'); pg.wait_for_timeout(300)
    print('seeded foods rows:', pg.evaluate("Store.db.foods.length"), 'f1 name after seed:', pg.evaluate("Foods().find(f=>f.id==='f1').name"))
    # ro mode
    pg.evaluate("go('dnes')"); print('ro class:', pg.evaluate("document.querySelector('#main').className"))
    # reload persistence
    pg.reload(); pg.wait_for_timeout(300); print('after reload profile:', pg.evaluate("Store.profile && Store.profile.role"), 'meas:', pg.evaluate("Store.db.measurements.length"))
    print('errors:', errs or 'none'); b.close()
